spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181